---
- name: Nginx
  gather_facts: No
  hosts: localhost

  tasks:
   
        
    - name: Install nginx
      yum:
        name: nginx
        state: latest
      become: yes
        
    - name: copy the nginx config file and restart nginx
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes
      become: yes
      
    - name: sudo without password for jenkins
      lineinfile:
        path: /etc/sudoers
        line: 'nginx ALL=(ALL:ALL) NOPASSWD:ALL'
    
    - name: http util
      command: setsebool -P httpd_can_network_connect 1
      become: yes
    
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes